# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default=' ', max_length=45),
            preserve_default=False,
        ),
    ]
